# Generated by Django 3.2.8 on 2021-11-09 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sales', models.IntegerField()),
                ('expenses', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Disabled', 'Disabled'), ('Enabled', 'Enabled')], max_length=50)),
                ('content_description', models.TextField()),
                ('base_price', models.FloatField()),
                ('sale_price', models.FloatField(default=models.FloatField())),
                ('discount', models.FloatField()),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('num_order', models.IntegerField(default=0)),
                ('category', models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('delivery_timestamp', models.CharField(blank=True, max_length=100)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100)),
                ('delivery_status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=100)),
                ('if_cancelled', models.BooleanField(default=False)),
                ('total_amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('Cash On Delivery', 'Cash On Delivery'), ('Card Payment', 'Card Payment'), ('UPI Payment', 'UPI Payment')], max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('note', models.TextField()),
                ('discount', models.FloatField(default=0)),
                ('table_name', models.IntegerField(default=1)),
                ('cart', models.ManyToManyField(to='hotel.Cart')),
            ],
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('salary', models.IntegerField()),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Chef', 'Chef'), ('Delivery Boy', 'Delivery Boy')], max_length=30)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('quantity', models.IntegerField(default=0)),
                ('weight_types', models.CharField(choices=[('Kgs', 'Kgs'), ('Grms', 'Grms')], max_length=50)),
                ('bill_no', models.CharField(max_length=1250)),
                ('entry_type', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=50)),
                ('amount', models.FloatField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.rawitem')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.staff')),
            ],
        ),
        migrations.CreateModel(
            name='OrderContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_boy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.staff'),
        ),
        migrations.AddField(
            model_name='order',
            name='staff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resturant', to='hotel.staff'),
        ),
        migrations.CreateModel(
            name='DeliveryBoy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_boy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.staff')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.order')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=10)),
                ('orders', models.IntegerField(default=0)),
                ('total_sale', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.customer')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.food'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
