# Generated by Django 3.2.8 on 2021-11-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_foodcategories'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='food',
            name='course',
            field=models.CharField(max_length=100),
        ),
    ]
