# Generated by Django 3.2.8 on 2021-11-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_dailypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypayment',
            name='billNo',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
