# Generated by Django 3.2.8 on 2021-11-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20211104_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
