# Generated by Django 3.2.8 on 2021-11-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_stock_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table_name',
            field=models.IntegerField(default=1),
        ),
    ]
